version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_PORT
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - NODE_ENV=production
    expose:
      - "${VIRTUAL_PORT}"

networks:
  default:
    external:
      name: nginx-proxy
