version: "3.7"

services:
  app:
    image: node:12
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=local
    volumes:
      - ".:/home/node/app"
    ports:
      - "${VIRTUAL_PORT}:${VIRTUAL_PORT}"
    command: tail -f /dev/null
