version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - VIRTUAL_PORT
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    ports:
      - "${VIRTUAL_PORT}"

networks:
  default:
    external:
      name: nginx-proxy
